<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>midterm-answers</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Midterm-answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="Midterm-answers_files/libs/quarto-html/quarto.js"></script>
<script src="Midterm-answers_files/libs/quarto-html/popper.min.js"></script>
<script src="Midterm-answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Midterm-answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="Midterm-answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Midterm-answers_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Midterm-answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Midterm-answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Midterm-answers_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<p>###add visualization package to make the colors better###</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install and load the wesanderson package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"wesanderson"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) {</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">install.packages</span>(<span class="st">"wesanderson"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="do">### add Wes Anderson palette for aesthetics </span><span class="al">###</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wesanderson)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>ff <span class="ot">&lt;-</span> <span class="fu">wes_palette</span>(<span class="st">"FantasticFox1"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>dj <span class="ot">&lt;-</span> <span class="fu">wes_palette</span>(<span class="st">"Darjeeling2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Directions:</strong> In this project, you will apply various statistical procedures covered in our course. Ensure to load the necessary R packages, including ‘openintro’ and ‘tidyverse’, render the <code>library()</code> function given above.</p>
<p>This code chunk below indicates how to load your data. If you use an OpenIntro data set, simply use <code>data()</code> function to load your data. If your data set is coming from any website as a .csv file, use <code>read_csv()</code> function to load it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data(datasetname) OR</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># midtermdata &lt;- read_csv("data-set-name.csv")</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(nyc_marathon)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(smoking)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mammals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="part-1-getting-to-know-your-data-set" class="level1">
<h1>Part 1: Getting to Know Your Data Set</h1>
<p><strong>Question 1: Use the <code>glimpse()</code> function to introduce your data set. Write a short paragraph explaining key aspects.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(nyc_marathon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 102
Columns: 7
$ year     &lt;dbl&gt; 1970, 1970, 1971, 1971, 1972, 1972, 1973, 1973, 1974, 1974, 1…
$ name     &lt;chr&gt; "Gary Muhrcke", NA, "Norman Higgins", "Beth Bonner", "Sheldon…
$ country  &lt;chr&gt; "United States", NA, "United States", "United States", "Unite…
$ time     &lt;time&gt; 02:31:38,       NA, 02:22:54, 02:55:22, 02:27:52, 03:08:41, …
$ time_hrs &lt;dbl&gt; 2.527222, NA, 2.381667, 2.922778, 2.464444, 3.144722, 2.36500…
$ division &lt;chr&gt; "Men", "Women", "Men", "Women", "Men", "Women", "Men", "Women…
$ note     &lt;chr&gt; "Course record", "No woman finishers", "Course record", "Worl…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(smoking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,691
Columns: 12
$ gender                &lt;fct&gt; Male, Female, Male, Female, Female, Female, Male…
$ age                   &lt;int&gt; 38, 42, 40, 40, 39, 37, 53, 44, 40, 41, 72, 49, …
$ marital_status        &lt;fct&gt; Divorced, Single, Married, Married, Married, Mar…
$ highest_qualification &lt;fct&gt; No Qualification, No Qualification, Degree, Degr…
$ nationality           &lt;fct&gt; British, British, English, English, British, Bri…
$ ethnicity             &lt;fct&gt; White, White, White, White, White, White, White,…
$ gross_income          &lt;fct&gt; "2,600 to 5,200", "Under 2,600", "28,600 to 36,4…
$ region                &lt;fct&gt; The North, The North, The North, The North, The …
$ smoke                 &lt;fct&gt; No, Yes, No, No, No, No, Yes, No, Yes, Yes, No, …
$ amt_weekends          &lt;int&gt; NA, 12, NA, NA, NA, NA, 6, NA, 8, 15, NA, NA, NA…
$ amt_weekdays          &lt;int&gt; NA, 12, NA, NA, NA, NA, 6, NA, 8, 12, NA, NA, NA…
$ type                  &lt;fct&gt; , Packets, , , , , Packets, , Hand-Rolled, Packe…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mammals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 62
Columns: 11
$ species      &lt;fct&gt; Africanelephant, Africangiantpouchedrat, ArcticFox, Arcti…
$ body_wt      &lt;dbl&gt; 6654.000, 1.000, 3.385, 0.920, 2547.000, 10.550, 0.023, 1…
$ brain_wt     &lt;dbl&gt; 5712.0, 6.6, 44.5, 5.7, 4603.0, 179.5, 0.3, 169.0, 25.6, …
$ non_dreaming &lt;dbl&gt; NA, 6.3, NA, NA, 2.1, 9.1, 15.8, 5.2, 10.9, 8.3, 11.0, 3.…
$ dreaming     &lt;dbl&gt; NA, 2.0, NA, NA, 1.8, 0.7, 3.9, 1.0, 3.6, 1.4, 1.5, 0.7, …
$ total_sleep  &lt;dbl&gt; 3.3, 8.3, 12.5, 16.5, 3.9, 9.8, 19.7, 6.2, 14.5, 9.7, 12.…
$ life_span    &lt;dbl&gt; 38.6, 4.5, 14.0, NA, 69.0, 27.0, 19.0, 30.4, 28.0, 50.0, …
$ gestation    &lt;dbl&gt; 645, 42, 60, 25, 624, 180, 35, 392, 63, 230, 112, 281, NA…
$ predation    &lt;int&gt; 3, 3, 1, 5, 3, 4, 1, 4, 1, 1, 5, 5, 2, 5, 1, 2, 2, 2, 1, …
$ exposure     &lt;int&gt; 5, 1, 1, 2, 5, 4, 1, 5, 2, 1, 4, 5, 1, 5, 1, 2, 2, 2, 2, …
$ danger       &lt;int&gt; 3, 3, 1, 3, 4, 4, 1, 4, 1, 1, 4, 5, 2, 5, 1, 2, 2, 2, 1, …</code></pre>
</div>
</div>
<p>The New York City Marathon dataset includes marathon times of winners in the New York City Marathon from 1970 to 2020.</p>
<p><strong>Question 2: Determine the number of variables and cases in the data set.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nyc_marathon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      year          name             country              time         
 Min.   :1970   Length:102         Length:102         Length:102       
 1st Qu.:1982   Class :character   Class :character   Class1:hms       
 Median :1995   Mode  :character   Mode  :character   Class2:difftime  
 Mean   :1995                                         Mode  :numeric   
 3rd Qu.:2008                                                          
 Max.   :2020                                                          
                                                                       
    time_hrs       division             note          
 Min.   :2.085   Length:102         Length:102        
 1st Qu.:2.166   Class :character   Class :character  
 Median :2.386   Mode  :character   Mode  :character  
 Mean   :2.350                                        
 3rd Qu.:2.456                                        
 Max.   :3.145                                        
 NA's   :3                                            </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(smoking)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    gender         age          marital_status       highest_qualification
 Female:965   Min.   :16.00   Divorced :161    No Qualification :586      
 Male  :726   1st Qu.:34.00   Married  :812    GCSE/O Level     :308      
              Median :48.00   Separated: 68    Degree           :262      
              Mean   :49.84   Single   :427    Other/Sub Degree :127      
              3rd Qu.:65.50   Widowed  :223    Higher/Sub Degree:125      
              Max.   :97.00                    A Levels         :105      
                                               (Other)          :178      
   nationality    ethnicity              gross_income
 English :833   Asian  :  41   5,200 to 10,400 :396  
 British :538   Black  :  34   10,400 to 15,600:268  
 Scottish:142   Chinese:  27   2,600 to 5,200  :257  
 Other   : 71   Mixed  :  14   15,600 to 20,800:188  
 Welsh   : 66   Refused:  13   20,800 to 28,600:155  
 Irish   : 23   Unknown:   2   Under 2,600     :133  
 (Other) : 18   White  :1560   (Other)         :294  
                    region    smoke       amt_weekends    amt_weekdays  
 London                :182   No :1270   Min.   : 0.00   Min.   : 0.00  
 Midlands &amp; East Anglia:443   Yes: 421   1st Qu.:10.00   1st Qu.: 7.00  
 Scotland              :148              Median :15.00   Median :12.00  
 South East            :252              Mean   :16.41   Mean   :13.75  
 South West            :157              3rd Qu.:20.00   3rd Qu.:20.00  
 The North             :426              Max.   :60.00   Max.   :55.00  
 Wales                 : 83              NA's   :1270    NA's   :1270   
                      type     
                        :1270  
 Both/Mainly Hand-Rolled:  10  
 Both/Mainly Packets    :  42  
 Hand-Rolled            :  72  
 Packets                : 297  
                               
                               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mammals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   species      body_wt            brain_wt      
 Africanelephant       : 1   Min.   :   0.005   Min.   :   0.14  
 Africangiantpouchedrat: 1   1st Qu.:   0.600   1st Qu.:   4.25  
 ArcticFox             : 1   Median :   3.342   Median :  17.25  
 Arcticgroundsquirrel  : 1   Mean   : 198.790   Mean   : 283.13  
 Asianelephant         : 1   3rd Qu.:  48.202   3rd Qu.: 166.00  
 Baboon                : 1   Max.   :6654.000   Max.   :5712.00  
 (Other)               :56                                       
  non_dreaming       dreaming      total_sleep      life_span      
 Min.   : 2.100   Min.   :0.000   Min.   : 2.60   Min.   :  2.000  
 1st Qu.: 6.250   1st Qu.:0.900   1st Qu.: 8.05   1st Qu.:  6.625  
 Median : 8.350   Median :1.800   Median :10.45   Median : 15.100  
 Mean   : 8.673   Mean   :1.972   Mean   :10.53   Mean   : 19.878  
 3rd Qu.:11.000   3rd Qu.:2.550   3rd Qu.:13.20   3rd Qu.: 27.750  
 Max.   :17.900   Max.   :6.600   Max.   :19.90   Max.   :100.000  
 NA's   :14       NA's   :12      NA's   :4       NA's   :4        
   gestation        predation        exposure         danger     
 Min.   : 12.00   Min.   :1.000   Min.   :1.000   Min.   :1.000  
 1st Qu.: 35.75   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.000  
 Median : 79.00   Median :3.000   Median :2.000   Median :2.000  
 Mean   :142.35   Mean   :2.871   Mean   :2.419   Mean   :2.613  
 3rd Qu.:207.50   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000  
 Max.   :645.00   Max.   :5.000   Max.   :5.000   Max.   :5.000  
 NA's   :4                                                       </code></pre>
</div>
</div>
<p>The New York City Marathon dataset includes 102 observations with 7 variables.</p>
<p>The mammals dataset contains 62 observations with 11 variables.</p>
<p><strong>Question 3: Identify the types of variables in the data set (nominal, ordinal, discrete, and continuous).</strong></p>
<p>The New York City Marathon dataset has three nominal variables in it being the <code>names</code> of the runners, their competition <code>division</code>, and their <code>country</code> of origin. The discrete variables being the <code>time</code> the runners completed the marathon in. There are continuous variables being the <code>year</code> which the runners participated in the marathon.</p>
<p>The mammals dataset has a single nominal variable being the <code>species</code> of mammal and the rest are discrete variables, which include <code>x</code> and <code>y</code> and <code>z</code>.</p>
<p><strong>Question 4: Choose a numeric variable and visualize its distribution. Describe the graph.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mammals,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> gestation)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">30</span>, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> dj[<span class="dv">5</span>], </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> dj[<span class="dv">3</span>])<span class="sc">+</span>  </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Gestation Period (days)"</span>, </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Midterm-answers_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="the-distribution-is-skewed-to-the-right-based-on-visual-interpretation.-tests-for-skewness-would-include-xyz" class="level3">
<h3 class="anchored" data-anchor-id="the-distribution-is-skewed-to-the-right-based-on-visual-interpretation.-tests-for-skewness-would-include-xyz">The distribution is skewed to the right based on visual interpretation. Tests for skewness would include: xyz</h3>
<p><strong>Question 5: Choose a categorical variable and create a visualization. Describe the graph.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the order of income levels</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust these levels based on the actual data 'gross_income' column</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>income_levels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Under 2,600"</span>, <span class="st">"2,600 to 5,200"</span>, <span class="st">"5,200 to 10,400"</span>, <span class="st">"10,400 to 15,600"</span>, <span class="st">"15,600 to 20,800"</span>, <span class="st">"20,800 to 26,000"</span>, <span class="st">"26,000 to 31,200"</span>,<span class="st">"31,200 to 36,400"</span>, <span class="st">"36,400 to 41,600"</span>, <span class="st">"Over 41,600"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Reclassify 'gross_income' as an ordered factor</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>smoking<span class="sc">$</span>income_order <span class="ot">&lt;-</span> <span class="fu">factor</span>(smoking<span class="sc">$</span>gross_income,<span class="at">levels =</span> income_levels, <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> smoking,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>income_order, <span class="at">y=</span>age)) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> dj[<span class="dv">5</span>], </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> dj[<span class="dv">3</span>])<span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Annual Income Level (GBP)"</span>, </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Age Distribution (years)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm-answers_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Type your answer here</p>
<p><strong>Question 6: Use the geom_point() function to plot a graph showing the linear relationship between two numeric variables, colored by a categorical variable.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">### first attempt was to use two continuous variables from mammals data, but coloring by a categorical value was difficult as each species  is unique </span><span class="al">###</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">na.omit</span>(mammals),</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> body_wt,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> gestation,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">color=</span> species)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span> <span class="co">#transform x axis</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Body Weight (kg) (log10 transformed)"</span>, </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gestation (days)"</span>)<span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm-answers_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">### second attempt was to use  </span><span class="al">###</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">na.omit</span>(smoking),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> age,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> amt_weekends,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">color=</span> marital_status)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Age of Smoker (years)"</span>, </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Weekend Cigarettes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Midterm-answers_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The first plot showed the difficulty of having unique categorical values for each row. In this case <code>species</code> had a unique value for each row and could not render the legend.</p>
<p>In the second plot, using the <code>smoking</code> data, the relationship between <code>age</code> of smoker and the number of cigarettes smoked on the weekend <code>amt_weekend</code> is shown as a function of <code>marital_status</code>. In this case, there are several interesting relationships. Perhaps not surprisingly smokers that are widowed tend to be older, and single smokers tend to be younger. There appears to be no relationship, however, between age and number of cigarettes on the weekend, or with marital status. A potential postive correlation for single smokers, based on the plot, could be present indicating that older, single smokers smoke more cigarettes on the weekend, but that would need to be tested separately by subsetting those data and running a correlation test.</p>
</section>
</section>
<section id="part-2-statistical-inference" class="level1">
<h1>Part 2: Statistical Inference</h1>
<p>In this section, you’ll perform inferential statistics tests using your data set.</p>
<section id="one-sample-t-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-t-test">One Sample <span class="math inline">\(t\)</span>-test</h2>
<p><strong>In this section, you are expected to write a case study based on your data set. In other words, choose a numeric variable and conduct a One Sample <span class="math inline">\(t\)</span>-test. Show your work.</strong></p>
<p>Type your case here.</p>
<p><strong>Question 7.1: What is the research question of this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 7.2: What type of variable do we have in this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 7.3: List the assumptions required for this test and check the assumption of normality for this study. Interpret the assumptions overall.</strong></p>
<ul>
<li><p><strong>Random Sampling:</strong> Explain here.</p></li>
<li><p><strong>Independence of Observation:</strong> Explain here.</p></li>
<li><p><strong>Normal Distribution:</strong> Explain here.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here to check normality.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Interpret your outputs here.</p>
<p><strong>Question 7.4. Use a one sample <span class="math inline">\(t\)</span>-test to investigate your research hypothesis. Answer the questions given below. Show your work.</strong></p>
<p><strong>Question 7.4.1 Write out the null and alternative hypotheses in words, in the context of this study.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 7.4.2. Determine the (<span class="math inline">\(\alpha\)</span>) level.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 7.4.3. Calculate the t-statistic and explain what you see in the output.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Type your answer here.</p>
<p><strong>Question 7.4.4. Draw a conclusion and write a conclusion statement.</strong></p>
<p>Type your answer here.</p>
</section>
<section id="independent-samples-t-test" class="level2">
<h2 class="anchored" data-anchor-id="independent-samples-t-test">Independent Samples <em>t</em> test</h2>
<p><strong>In this section, you are expected to write a case study based on your data set. Choose a numeric variable and a categorical variable (with 2 CATEGORIES) conduct Independent Samples <span class="math inline">\(t\)</span>-test. Show your work.</strong></p>
<p><strong>Question 8.1. What is the research question of this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 8.2. What type of variable do we have in this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 8.3. List the assumptions required for this test and check the assumption of normality for this study. Interpret the assumptions overall.</strong></p>
<p><em>Random Sampling:</em> Explain here.</p>
<p><em>Independence of Observation:</em> Explain here.</p>
<p><em>Normal Distribution:</em> Explain here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here to check normality</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Interpret the assumptions and type your reasoning.</p>
<p><strong>Question 8.4. Use an independent samples <span class="math inline">\(t\)</span>-test to investigate your research hypothesis. Answer the questions given below. Show your work.</strong>__</p>
<p><strong>Question 8.4.1 Write out the null and the alternative hypothesis in words, in the context of this study:</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 8.4.2. Determine the (<span class="math inline">\(\alpha\)</span>) level.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 8.4.3. Calculate t statistic and explain what you see in the output.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Type your answer here.</p>
<p><strong>Question 8.4.4. Explain what each function does in this question.</strong></p>
<p><code>t_test</code>: Type your answer here.</p>
<p><code>formula</code>:Type your answer here.</p>
<p><code>order</code>: Type your answer here.</p>
<p><code>alternative</code>: Type your answer here.</p>
<p><code>conf.level</code>: Type your answer here.</p>
<p><code>var.equal</code>: Type your answer here.</p>
<p><strong>Question 8.4.5. Draw a conclusion and write a conclusion statement</strong></p>
<p>Type your answer here.</p>
</section>
<section id="one-way-anova" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova">One Way ANOVA</h2>
<p>Write a case study based on your data set. Choose a numeric variable and a categorical variable (more than 2 categories) conduct One Way ANOVA. Show your work.</p>
<p><strong>Question 9.1. What is the research question of this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 9.2. What type of variable do we have in this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 9.3. List the assumptions required for this test and check the assumption of normality for this study. Interpret the assumptions overall.</strong></p>
<p>List the assumptions here and explain them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here to check normality</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Interpret the assumptions and type your reasoning.</p>
<p><strong>Question 9.4. Conduct One Way ANOVA to investigate your research hypothesis. Answer the questions given below. Show your work.</strong>__</p>
<p><strong>Question 9.4.1 Write out the null and alternative hypotheses in words, in the context of this study.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 9.4.2. Determine the (<span class="math inline">\(\alpha\)</span>) level.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 9.4.3. Calculate F statistic and explain what you see in the output.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Type your answer here.</p>
<p><strong>Question 9.4.4. Explain what each function does in this question.</strong></p>
<p><strong>Question 9.4.5. Draw a conclusion and write a conclusion statement</strong></p>
<p>Type your answer here.</p>
</section>
<section id="chi-square-test" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test">Chi Square Test</h2>
<p>Write a case study based on your data set. Choose a 2 categorical variable conduct Chi-square test. Show your work.</p>
<p><strong>Question 10.1. What is the research question of this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 10.2. What type of variable do we have in this study?</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 10.3. Please list the assumptions required for this test. Interpret the assumptions overall.</strong></p>
<p>List the assumptions here and explain them. Interpret the assumptions and type your reasoning.</p>
<p><strong>Question 10.4. Conduct a Chi-square test to investigate your research question</strong></p>
<p><strong>Question 10.4.1 Write out the null &amp; the alternative hypothesis in words, in the context of this study:</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 10.4.2. Determine the (<span class="math inline">\(\alpha\)</span>) level.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 10.4.3. Calculate Chi-square statistic and explain what you see in the output.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Type your codes here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Type your answer here.</p>
<p><strong>Question 10.4.4. Explain what each function does in this question.</strong></p>
<p>Type your answer here.</p>
<p><strong>Question 10.4.5. Draw a conclusion and write a conclusion statement</strong></p>
<p>Type your answer here.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>